name: Docker Deploy Production

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Short SHA to deploy'
        required: true

env:
  REGISTRY: ${{ env.REGISTRY }}
  IMAGE_NAME: ${{ env.IMAGE_NAME }}

jobs:
  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Pull image by SHA
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.sha }}

      - name: Retag image as uction
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.sha }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod

      - name: Push production image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod
