name: Docker Deploy Production

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: 'Run ID of the Build workflow to fetch the SHA'
        required: true

env:
  REGISTRY: ${{ env.REGISTRY }}
  IMAGE_NAME: ${{ env.IMAGE_NAME }}

jobs:
  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}


      - name: GitHub Slug Action
        id: slug
        uses: rlespinasse/github-slug-action@v4

      - name: Pull image by SHA
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }}

      - name: Retag image as uction
        run: docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA_SHORT }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod

      - name: Push production image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod
